name: Next CI/CD

on:
  push:
    branches: [Production,Developing]

jobs:
  lintTest:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Clone Repostitory
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: |
          echo "Running Installing Dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running Linting tests..."
          npm run lint
        env:
          CI: true
  securityCheck:
    name: Security Check
    runs-on: self-hosted
    steps:
    - name: Check for Security
      run: |
        echo "Running Security Chechks .."
        sleep 5;
        echo "Running Security Chechks .. 1"
        sleep 5;
        echo "Running Security Chechks .. 2"
        sleep 5;
        echo "Running Security Chechks .. 3"
        sleep 5;

  deploy:
    name: Deployment
    runs-on: self-hosted
    needs: [lintTest, securityCheck]
    steps:
      - name: Install Dependencies
        run: |
          echo "Deployment in Progress.."